
	<section id="avatar-url-help">
		<header>
			<h1>Profile Pictures(avatars) on kenstowell.net</h1>
		</header>
		<section>
			<p>
				I'm not cool enough to want to architect a way to store a ton of users' profile pictures
				on my site so I require that if you want to use one you need to provide me a link for it so
				that I won't use up all that precious disk space.
			</p>
			<p>
				If you use Gravatar - you can leave this spot blank because I just use your email
				address for the API they have set up.
			</p>
			<p>
				Honestly, if you participate on a lot of forums, I reccommend <a href="http://gravatar.com" target="_blank">Gravatar</a>, they make having a picture easy
				stuff.
			</p>
		</section>
	</section>
	<section id="overlay"></section>