<div id="email-wrapper" style="width:360px; height: 520px; background: url('http://i1170.photobucket.com/albums/r538/alsa-admin/concrete_wall_2.png') repeat;
margin: 0 auto 0 auto; text-align: center;">
	<div id="content-wrapper" style="background: url('http://i1170.photobucket.com/albums/r538/alsa-admin/email_footer_bg.png') no-repeat 0 100%;
			height:100%; width:100%;">
		<div id="header"
			 style="width: 100%; height:48px; background: url('http://i1170.photobucket.com/albums/r538/alsa-admin/email_header_bg.png') no-repeat 0 0; font-family: helvetica;
		 font-size:10px; text-align: center; margin: 0; padding: 0;">
			<p style="padding-top:35px">kenstowell.net username recovery</p>
		</div>
		<div id="email_body" style="padding:10px; margin:35px 0 0 0; text-align: left; color: #a89a8a; font-family: helvetica;">
			<div id="email_title">
				<h1>you@you.com</h1>
			</div>
			<div id="forgot-username-copy" style="font-family: helvetica; margin: 50px 0 0 0; font-size: 13px;">
				<p>You are receiving this email because you forgot your username.  The username associated with this email is:</p>
			</div>
			<div id="username" style="color:#4b4b4b; text-align: center; margin: 50px 0 0 0;">
				<h1><a href="http://code.kenstowell.local/" style="color:#4b4b4b;">KTS_ADMIN</a></h1>
			</div>
			<div id="forgot-username-footer-copy" style="margin:50px 0 0 0; font-family: helvetica; font-size: 13px; text-align: center;">
				<p>Thanks for using my site and I hope you continue to do so! In the mean time, here are some links you might find helpful:</p>
				<a href="http://www.puritan.com/ginkgo-biloba-052/ginkgo-biloba-120-mg-capsules-004544" target="_blank" style="display: block;">Ginko Biloba</a>
				<a href="http://www.helpguide.org/life/improving_memory.htm" style="display: block;">Memory enhancement</a>
				<p>;)</p>
			</div>
		</div>
	</div>
</div>