<section id="home" class="content-wrapper row">
	<header id="home-header">

	</header>
	<article class="twelvecol">
		<p>
			The surface is fine and powdery. I can kick it up loosely with my toe. It does adhere in fine layers,
			like powdered charcoal, to the sole and sides of my boots. I only go in a small fraction of an inch,
			maybe an eighth of an inch, but I can see the footprints of my boots and the treads in the fine, sandy
			particles. There seems to be no difficult in moving around, as we suspected.
		</p>
	</article>
</section>