<?php echo $this->doctype()?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headScript(); ?>
	</head>
	<body>
		<div id="crosshairs"></div>
		<header id="main-header">
			<nav id="main-nav">
				<ul id="main-nav-list">
					<li class="main-nav-list-item"><a href="home" id="main-nav-link-home" class="main-nav-link">Home</a></li>
					<li class="main-nav-list-item"><a href="services" id="main-nav-link-services" class="main-nav-link">Services</a></li>
					<li class="main-nav-list-item"><a href="work" id="main-nav-link-work" class="main-nav-link">Work</a></li>
					<li class="main-nav-list-item"><a href="blog" id="main-nav-link-blog" class="main-nav-link">Blog</a></li>
					<li class="main-nav-list-item"><a href="tutorials" id="main-nav-link-tutorials" class="main-nav-link">Tutorials</a></li>
					<li class="main-nav-list-item"><a href="code" id="main-nav-link-code" class="main-nav-link">Code</a></li>
					<li class="main-nav-list-item"><a href="contact" id="main-nav-link-contact" class="main-nav-link">Contact</a></li>
				</ul>
			</nav>
		</header>
		<section id="side-panel">
			<section id="side-panel-toggle">
				<section id="arrow" class="left-arrow">
				</section>
			</section>
			<section id="side-panel-content">
				<?php echo $this->action('index', 'side-panel', null); ?>
			</section>
		</section>
		<div id="page-wrapper">
			<?php echo $this->layout()->content; ?>
		</div>
		<?php echo $this->action('index', 'epic-help', null); ?>
		<section id="loader">
			<img src="/images/index/loader.gif" alt="bleep bloop">
		</section>
	</body>
</html>